# Example GitHub Actions workflow for PR Review CLI

name: Code Review

on:
  pull_request:
    branches: [main, develop]

jobs:
  review:
    runs-on: ubuntu-latest

    services:
      ollama:
        image: ollama/ollama:0.4.0
        ports:
          - 11434:11434
        options: >-
          --health-cmd "curl -f http://localhost:11434/api/tags || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install PR Review CLI
        run: npm install -g pull-request-reviewer-ai

      - name: Wait for Ollama
        run: |
          until curl -f http://localhost:11434/api/tags; do
            echo "Waiting for Ollama..."
            sleep 2
          done

      - name: Pull Ollama model
        run: |
          curl http://localhost:11434/api/pull -d '{"name": "deepseek-coder:1.3b"}'
        timeout-minutes: 10

      - name: Run code review
        run: |
          pr-review compare ${{ github.head_ref }} ${{ github.base_ref }} \
            --format json \
            --output review.json \
            --exit-code
        env:
          LLM_ENDPOINT: http://localhost:11434
          LLM_MODEL: deepseek-coder:1.3b
          LLM_PROVIDER: ollama
          LLM_TEMPERATURE: '0'
          LLM_SEED: '42'
        continue-on-error: true

      - name: Upload review as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-review
          path: review.json

      - name: Comment PR with review
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const fs = require('fs');
            const review = JSON.parse(fs.readFileSync('review.json', 'utf8'));

            const summary = review.summary;
            const comment = `## Code Review Results

            **Files Reviewed:** ${summary.filesReviewed}
            **Total Issues:** ${summary.totalIssues}
            **Score:** ${summary.score}/10

            ### Issues by Severity
            - Critical: ${summary.critical}
            - High: ${summary.high}
            - Medium: ${summary.medium}
            - Low: ${summary.low}
            - Info: ${summary.info}

            [View full review](./review.json)`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
